Final cleanup for 2.0.0 release
trilinos/ForTrilinos pull request #282
Opened 2020-09-25 02:57 UTC by sethrj

- Add verbosity to the anasazi output to debug it
- Don't fail when solver doesn't converge -- eigenvalues may be right but just to a lower tolerance
- Add accessors to determine convergence and iteration count
- Re-enable formerly failing tests and add additional tetsing
- Remove zombie files

2020-09-25 02:57 UTC, sethrj commented
I can do a clang-format on the source code in another PR just to keep things clean.

2020-11-19 20:36 UTC, aprokop commented
retest this please

2020-11-23 15:15 UTC, aprokop requested changes
Solid work. I have just a few minor comments and questions.

2020-11-23 15:15 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.hpp
> +    int max_eigenvalues() const;
What is the use case for this function? Also, the comment seems to indicate as if its purpose is to specify that value, instead of getting it out?

2020-11-23 15:15 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.cpp
> +    paramList_ = paramList;
Why would we want to store it? In fact, I'm not sure why there is `paramList_` in the first place.

2020-11-23 15:15 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.cpp
> +                                 Teuchos::ArrayView<int> eigenIndex) {
Not a fan, but I see why you need it. Could also make `converged_` and friends `mutable`.

2020-11-23 15:15 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.cpp
> +          << numIters_ << " iterations" << std::endl;
This may not follow xSDK or E4S policies about not hardcoding output.

2020-11-23 15:15 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.cpp
> +    return numConverged;
This changes the meaning. What do we actually want eigensolver to return? Number of converged values, or the size of the array with eigenvalues? The issue is that if it's the former, there is no easy way to get the size of the latter.

2020-11-24 14:28 UTC, sethrj commented on ROADMAP.md
> -# ForTrilinos roadmap
As you say, it was a pain to maintain and I don't think it *was* being maintained; I think it was a relic of when we first started. I didn't think it provided anything particularly useful -- I think our time would be better spent trying to autodocument the fortran interface.

2020-11-24 14:32 UTC, sethrj commented on src/fortrilinos_hl/solver_handle.hpp
> +    explicit TrilinosSolver(const Teuchos::RCP<const Teuchos::Comm<int>>& comm);
I generally prefer to keep implementation details out of the main header files (the DefaultComm header would have to move to the `.hpp`), and I also generally prefer not to use default arguments in C++.

2020-11-24 14:37 UTC, sethrj commented on src/fortrilinos_hl/solver_handle.hpp
> -    void operator=(const TrilinosSolver&) = delete;
These methods were ignored by SWIG anyway (none of the assignment/copying logic changed in the wrapper code) and there's nothing mechanically wrong with copying the classes -- so I figured the deleted methods didn't need to be here.

2020-11-24 14:38 UTC, sethrj commented on test/fortrilinos_hl/data/davidson.xml
> +    <Parameter name="debug: graph level" type="int" value="4"/>
Haha good point -- I was digging around trying to figure out what was going on with the convergence.

2020-11-24 14:41 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.hpp
> +    explicit TrilinosEigenSolver(const Teuchos::RCP<const Teuchos::Comm<int>>& comm);
I guess it's a style preference, but I think having a default constructor and an explicit one-argument constructor is more clear than a combined constructor with a default argument. The SWIG code it generates is the same, anyway.

2020-11-24 14:44 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.hpp
> +    int max_eigenvalues() const;
To extract the results when you call `solve`, the arrays you pass from fortran have to be sized correctly in advance. This function is the way to get that value. I could see the comment being ambiguous; do you have a suggestion for an improved phrasing?

2020-11-24 14:44 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.cpp
> +    paramList_ = paramList;
I'm not sure... the `paramList_` member data was in there originally and left unused. I'll delete it.

2020-11-24 14:47 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.cpp
> +                                 Teuchos::ArrayView<int> eigenIndex) {
Since `solve` is changing the state of the managed `solver_` object regardless of the `converged_` status update, I think it's more semantically correct for the member function to be non-const.

2020-11-24 14:49 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.cpp
> +          << numIters_ << " iterations" << std::endl;
Ooh, good point. There's also a `cout` for the solve result in `solver_handle`. Should I just remove the cout in both places?

2020-11-24 15:03 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.cpp
> +    return numConverged;
I remember puzzling over this as well. I guess I assumed that unconverged eigenvalues would not be useful? And I thought the size of the array would be the same as `max_eigenvalues`.

2020-11-24 15:04 UTC, sethrj commented
@aprokop Thanks for the comments! I'm going to wait for your responses before pushing new changes.

2020-11-24 15:04 UTC, aprokop commented on ROADMAP.md
> -# ForTrilinos roadmap
One of the things it provided was whether there is a performance penalty for using a particular function, as some of them required copying arrays and doing +-1. However, as I personally am unlikely to spend time maintaining this, I cannot fault you for removing it.

2020-11-24 15:05 UTC, aprokop commented on src/fortrilinos_hl/solver_handle.hpp
> +    explicit TrilinosSolver(const Teuchos::RCP<const Teuchos::Comm<int>>& comm);
> I also generally prefer not to use default arguments in C++.

nani?! why?

2020-11-24 15:07 UTC, aprokop commented on src/fortrilinos_hl/solver_handle.hpp
> -    void operator=(const TrilinosSolver&) = delete;
My concern is that we don't make it clear the handle semantics. I.e., if you copy a handle, and modify its matrices, is that going affect the other copy? As of right now, it will, and that's not clear. I didn't realize that SWIG is ignoring them.

2020-11-24 15:10 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.hpp
> +    int max_eigenvalues() const;
My concern is with complex eigenvalues. If you look at how anasazi does them, the size of the arrays will depend on whether the found eigenvalue is real or complex. So, the number of eigenvalues by itself is not sufficient to make arrays of the right size (though, you *could* use it to provide an upper bound by multiplying it by 2). 

But my overall thinking is that a user is the one who constructs the parameter list to solve the eigenproblem. Thus, he has a knowledge of how many eigenvalues he/she needs and can use that to size the arrays.

2020-11-24 15:12 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.cpp
> +          << numIters_ << " iterations" << std::endl;
Either remove, or provide yet another option to control verbosity. I assume that this information can be gleaned after the call to `solve()`, if we add a function to get out the number of iterations.

2020-11-25 14:14 UTC, sethrj commented on src/fortrilinos_hl/solver_handle.hpp
> +    explicit TrilinosSolver(const Teuchos::RCP<const Teuchos::Comm<int>>& comm);
Mostly because they can get out of hand too quickly: I've seen constructors with like 5 optional int/double arguments (overloaded with other constructors as well) and when you see the code that calls the constructor it is impossible to tell what it's calling.

Having an indpendent empty constructor also makes the code more readable -- if I only saw the one-argument constructor I might not make it all the way to finding the default argument, especially when the type is so complex and the default value even more so.

Finally, the most concrete reason is that `explicit` doesn't work correctly with one-argument default constructors: see for example https://wg21.link/P0935R0 with changes to the default library.

2020-11-25 14:25 UTC, sethrj commented on src/fortrilinos_hl/solver_handle.hpp
> -    void operator=(const TrilinosSolver&) = delete;
That's true... the ever-present danger of shared pointers.

2020-11-25 14:44 UTC, aprokop commented on src/fortrilinos_hl/eigen_handle.cpp
> +    return numConverged;
If I remember this right, there is a second array of indices. 0 means it's a real eigenvalue, while 1 and -1 mean complex eigenvalue and its conjugate, respectively. So, you can get three eigenvalues, one real and 2 complex. In that situation, I don't recall what the `eValues` is going to be sized to.

2020-11-25 14:50 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.hpp
> +    int max_eigenvalues() const;
Oh really, I didn't realize that the array size depended on whether they were real. I knew that we required a factor of two space on the incoming vector for real/imaginary.

From a non-regular-trilinos-user perspective it wasn't immediately obvious to me (looking at existing test code) how to get the eigenvalues. And I really really dislike parameter lists as the primary means of communication between libraries: they're extremely fragile (consider the arbitrary capitalization and spelling of `NumEV`) and you literally have to dig into the source code (rather than looking at a class interface) to figure out what the names and types of parameters are. 😬

2020-11-25 15:10 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.cpp
> +          << numIters_ << " iterations" << std::endl;
I've removed it -- it'll be up to the caller to check and make sure the values are converged.

2020-11-25 15:11 UTC, sethrj commented on src/fortrilinos_hl/solver_handle.cpp
> +      std::cout << "solve result:" <<  status << std::endl;
Deleted this `cout` per our other discussion

2020-11-25 15:27 UTC, sethrj commented on src/fortrilinos_hl/eigen_handle.hpp
> +    explicit TrilinosEigenSolver(const Teuchos::RCP<const Teuchos::Comm<int>>& comm);
Actually I remembered the `explicit` correctness issue as I posted on the other constructor discussion --  closing.

2020-11-25 15:46 UTC, aprokop commented on src/fortrilinos_hl/fortrilinos_hl.i
> +%fortransubroutine ForTrilinos::TrilinosSolver::solve;
What does this do?

2020-11-25 15:46 UTC, aprokop commented on src/fortrilinos_hl/solver_handle.cpp
> +  double TrilinosSolver::solve(const Teuchos::RCP<const MultiVector>& B, Teuchos::RCP<MultiVector>& X) const {
Honestly, this is a weird signature of the function. I don't think it should return tolerance. The only thing user really cares about is whether it converged or not.

2020-11-25 18:01 UTC, sethrj commented on src/fortrilinos_hl/fortrilinos_hl.i
> +%fortransubroutine ForTrilinos::TrilinosSolver::solve;
Instead of being a function (reqiuring `tol = foo%solve(...)`) it changes the signature so that `solve` is still a subroutine, but it returns an optional value through an argument `foo%solve(..., tol)`. This lets us return the solution tolerance without requiring changes in existing code, and it makes more sense for solve to be a subroutine since it returns the solution as an argument anyway.

2020-11-25 18:02 UTC, sethrj commented on src/fortrilinos_hl/solver_handle.cpp
> +  double TrilinosSolver::solve(const Teuchos::RCP<const MultiVector>& B, Teuchos::RCP<MultiVector>& X) const {
OK, so we could make it return a bool instead. I was just trying to return the single scalar with the most information about the solve.

2020-11-29 15:53 UTC, sethrj commented
OK @aprokop , any more feedback? Were the earlier discussions resolved to your satisfaction?

2020-12-01 20:02 UTC, aprokop approved these changes

2020-12-01 20:05 UTC, merged